[package]
name = "xml-handler"
version = { workspace = true }
edition = "2021"

[dependencies]
quick-xml = { workspace = true }
thiserror = { workspace = true }
lazy_static = "1.4.0"
script-aggregator = { workspace = true }
tsp-toolkit-kic-lib = { workspace = true }
